/**
*auth
*/
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const AUTHENTICATED = 'AUTHENTICATED'
export const SET_ADMIN = 'SET_ADMIN'
export const SET_DOCTOR = 'SET_DOCTOR'
export const SET_DOCTORASSISTANT = 'SET_DOCTORASSISTANT'
/**
*organize
*/
export const ADD_ORGANIZE_REQUEST = 'ADD_ORGANIZE_REQUEST'
export const ADD_ORGANIZE_SUCCESS = 'ADD_ORGANIZE_SUCCESS'
export const ADD_ORGANIZE_FAILURE = 'ADD_ORGANIZE_FAILURE'

export const ORGANIZE_LIST_REQUEST = 'ORGANIZE_LIST_REQUEST'
export const ORGANIZE_LIST_SUCCESS = 'ORGANIZE_LIST_SUCCESS'
export const ORGANIZE_LIST_FAILURE = 'ORGANIZE_LIST_FAILURE'

export const ORGANIZE_EDIT_REQUEST = 'ORGANIZE_EDIT_REQUEST'
export const ORGANIZE_EDIT_SUCCESS = 'ORGANIZE_EDIT_SUCCESS'
export const ORGANIZE_EDIT_FAILURE = 'ORGANIZE_EDIT_FAILURE'

export const ORGANIZE_GET_REQUEST = 'ORGANIZE_GET_REQUEST'
export const ORGANIZE_GET_SUCCESS = 'ORGANIZE_GET_SUCCESS'
export const ORGANIZE_GET_FAILURE = 'ORGANIZE_GET_FAILURE'
/**
*lesson
*/
export const LESSON_ADD_REQUEST = 'LESSON_ADD_REQUEST'
export const LESSON_ADD_SUCCESS = 'LESSON_ADD_SUCCESS'
export const LESSON_ADD_FAILURE = 'LESSON_ADD_FAILURE'

export const LESSON_EDIT_REQUEST = 'LESSON_EDIT_REQUEST'
export const LESSON_EDIT_SUCCESS = 'LESSON_EDIT_SUCCESS'
export const LESSON_EDIT_FAILURE = 'LESSON_EDIT_FAILURE'

export const LESSON_INFO_REQUEST = 'LESSON_INFO_REQUEST'
export const LESSON_INFO_SUCCESS = 'LESSON_INFO_SUCCESS'
export const LESSON_INFO_FAILURE = 'LESSON_INFO_FAILURE'

export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST'
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS'
export const LESSON_LIST_FAILURE = 'LESSON_LIST_FAILURE'

export const LESSON_GET_REQUEST = 'LESSON_GET_REQUEST'
export const LESSON_GET_SUCCESS = 'LESSON_GET_SUCCESS'
export const LESSON_GET_FAILURE = 'LESSON_GET_FAILURE'

