/**
*auth
*/
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const AUTHENTICATED = 'AUTHENTICATED'
export const SET_ADMIN = 'SET_ADMIN'
export const SET_DOCTOR = 'SET_DOCTOR'
export const SET_DOCTORASSISTANT = 'SET_DOCTORASSISTANT'
/**
*organize
*/
export const ADD_ORGANIZE_REQUEST = 'ADD_ORGANIZE_REQUEST'
export const ADD_ORGANIZE_SUCCESS = 'ADD_ORGANIZE_SUCCESS'
export const ADD_ORGANIZE_FAILURE = 'ADD_ORGANIZE_FAILURE'

export const ORGANIZE_LIST_REQUEST = 'ORGANIZE_LIST_REQUEST'
export const ORGANIZE_LIST_SUCCESS = 'ORGANIZE_LIST_SUCCESS'
export const ORGANIZE_LIST_FAILURE = 'ORGANIZE_LIST_FAILURE'
export const ORGANIZE_MYLIST_SUCCESS = 'ORGANIZE_MYLIST_SUCCESS'

export const ORGANIZE_EDIT_REQUEST = 'ORGANIZE_EDIT_REQUEST'
export const ORGANIZE_EDIT_SUCCESS = 'ORGANIZE_EDIT_SUCCESS'
export const ORGANIZE_EDIT_FAILURE = 'ORGANIZE_EDIT_FAILURE'

export const ORGANIZE_GET_REQUEST = 'ORGANIZE_GET_REQUEST'
export const ORGANIZE_GET_SUCCESS = 'ORGANIZE_GET_SUCCESS'
export const ORGANIZE_GET_FAILURE = 'ORGANIZE_GET_FAILURE'

export const GET_ORGANIZE_INFO_SUCCESS = 'GET_ORGANIZE_INFO_SUCCESS'

export const SET_ORGANIZE_LIST_OFFSET = 'SET_ORGANIZE_LIST_OFFSET'
/**
*lesson
*/
export const LESSON_ADD_REQUEST = 'LESSON_ADD_REQUEST'
export const LESSON_ADD_SUCCESS = 'LESSON_ADD_SUCCESS'
export const LESSON_ADD_FAILURE = 'LESSON_ADD_FAILURE'

export const LESSON_EDIT_REQUEST = 'LESSON_EDIT_REQUEST'
export const LESSON_EDIT_SUCCESS = 'LESSON_EDIT_SUCCESS'
export const LESSON_EDIT_FAILURE = 'LESSON_EDIT_FAILURE'

export const LESSON_INFO_REQUEST = 'LESSON_INFO_REQUEST'
export const LESSON_INFO_SUCCESS = 'LESSON_INFO_SUCCESS'
export const LESSON_INFO_FAILURE = 'LESSON_INFO_FAILURE'

export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST'
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS'
export const LESSON_LIST_FAILURE = 'LESSON_LIST_FAILURE'

export const LESSON_GET_REQUEST = 'LESSON_GET_REQUEST'
export const LESSON_GET_SUCCESS = 'LESSON_GET_SUCCESS'
export const LESSON_GET_FAILURE = 'LESSON_GET_FAILURE'
/**
*area
*/
export const AREA_LIST_REQUEST = 'AREA_LIST_REQUEST'
export const AREA_LIST_SUCCESS = 'AREA_LIST_SUCCESS'
export const AREA_LIST_FAILURE = 'AREA_LIST_FAILURE'

export const GET_AREA_SUCCESS = 'GET_AREA_SUCCESS'

export const SET_SELECTED_AREA_SUCCESS = 'SET_SELECTED_AREA_SUCCESS'
/**
*upload
*/
export const UPLOAD_COVER_REQUEST = 'UPLOAD_COVER_REQUEST'
export const UPLOAD_COVER_SUCCESS = 'UPLOAD_COVER_SUCCESS'
export const UPLOAD_COVER_FAILURE = 'UPLOAD_COVER_FAILURE'
export const UPLOAD_YUNBOOK_REQUEST = 'UPLOAD_YUNBOOK_REQUEST'
export const UPLOAD_YUNBOOK_SUCCESS = 'UPLOAD_YUNBOOK_SUCCESS'
export const UPLOAD_YUNBOOK_FAILURE = 'UPLOAD_YUNBOOK_FAILURE'
/**
*yunbook
*/
export const YUNBOOK_ADD_REQUEST = 'YUNBOOK_ADD_REQUEST'
export const YUNBOOK_ADD_SUCCESS = 'YUNBOOK_ADD_SUCCESS'
export const YUNBOOK_ADD_FAILURE = 'YUNBOOK_ADD_FAILURE'

export const YUNBOOK_GET_REQUEST = 'YUNBOOK_GET_REQUEST'
export const YUNBOOK_GET_SUCCESS = 'YUNBOOK_GET_SUCCESS'
export const YUNBOOK_GET_FAILURE = 'YUNBOOK_GET_FAILURE'

export const YUNBOOK_LIST_SUCCESS = 'YUNBOOK_LIST_SUCCESS'
export const YUNBOOK_LIST_REQUEST = 'YUNBOOK_LIST_REQUEST'
export const YUNBOOK_LIST_FAILURE = 'YUNBOOK_LIST_FAILURE'

export const YUNBOOK_EDIT_REQUEST = 'YUNBOOK_EDIT_REQUEST'
export const YUNBOOK_EDIT_SUCCESS = 'YUNBOOK_EDIT_SUCCESS'
export const YUNBOOK_EDIT_FAILURE = 'YUNBOOK_EDIT_FAILURE'

export const YUNBOOK_INFO_REQUEST = 'YUNBOOK_INFO_REQUEST'
export const YUNBOOK_INFO_SUCCESS = 'YUNBOOK_INFO_SUCCESS'
export const YUNBOOK_INFO_FAILURE = 'YUNBOOK_INFO_FAILURE'

export const MYYUNBOOK_INFO_SUCCESS = 'MYYUNBOOK_INFO_SUCCESS'
export const MYYUNBOOK_LIST_SUCCESS = 'MYYUNBOOK_LIST_SUCCESS'
export const SET_YUNBOOK_LIST_OFFSET = 'SET_YUNBOOK_LIST_OFFSET'
export const SET_MYYUNBOOK_LIST_OFFSET = 'SET_MYYUNBOOK_LIST_OFFSET'
/**
 * section
 */
export const SECTION_ADD_REQUEST = 'SECTION_ADD_REQUEST'
export const SECTION_ADD_SUCCESS = 'SECTION_ADD_SUCCESS'
export const SECTION_ADD_FAILURE = 'SECTION_ADD_FAILURE'
/**
 * organizelesson
 */
export const ORGANIZELESSON_EDIT_REQUEST = 'ORGANIZELESSON_EDIT_REQUEST'
export const ORGANIZELESSON_EDIT_FAILURE = 'ORGANIZELESSON_EDIT_FAILURE'
export const ORGANIZELESSON_EDIT_SUCCESS = 'ORGANIZELESSON_EDIT_SUCCESS'

export const ORGANIZELESSON_GET_REQUEST = 'ORGANIZELESSON_GET_REQUEST'
export const ORGANIZELESSON_GET_SUCCESS = 'ORGANIZELESSON_GET_SUCCESS'
export const ORGANIZELESSON_GET_FAILURE = 'ORGANIZELESSON_GET_FAILURE'

export const ORGANIZELESSON_ADD_REQUEST = 'ORGANIZELESSON_ADD_REQUEST'
export const ORGANIZELESSON_ADD_SUCCESS = 'ORGANIZELESSON_ADD_SUCCESS'
export const ORGANIZELESSON_ADD_FAILURE = 'ORGANIZELESSON_ADD_FAILURE'

export const ORGANIZELESSON_LIST_REQUEST = 'ORGANIZELESSON_LIST_REQUEST'
export const ORGANIZELESSON_LIST_SUCCESS = 'ORGANIZELESSON_LIST_SUCCESS'
export const ORGANIZELESSON_LIST_FAILURE = 'ORGANIZELESSON_LIST_FAILURE'

export const ORGANIZELESSON_SLIST_SUCCESS = 'ORGANIZELESSON_SLIST_SUCCESS'
/**
 * user
 */
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
/**
 * lessonteam
 */
export const GET_TEAM_LIST_REQUEST = 'GET_TEAM_LIST_REQUEST'
export const GET_LESSONTEAM_LIST_REQUEST = 'GET_LESSONTEAM_LIST_REQUEST'
export const GET_LESSONTEAM_LIST_SUCCESS = 'GET_LESSONTEAM_LIST_SUCCESS'
export const GET_LESSONTEAM_LIST_FAILURE = 'GET_LESSONTEAM_LIST_FAILURE'

export const GET_TEAMINVITED_LIST_REQUEST = 'GET_TEAMINVITED_LIST_REQUEST'
export const GET_TEAMINVITED_LIST_SUCCESS = 'GET_TEAMINVITED_LIST_SUCCESS'
export const GET_TEAMINVITED_LIST_FAILURE = 'GET_TEAMINVITED_LIST_FAILURE'

export const REMOVE_LESSONTEAM_SUCCESS = 'REMOVE_LESSONTEAM_SUCCESS'

export const EDIT_LESSONTEAM_SUCCESS = 'EDIT_LESSONTEAM_SUCCESS'

export const GET_LESSONTEAM_INVITED_LIST_SUCCESS = 'GET_LESSONTEAM_INVITED_LIST_SUCCESS'